# Generated by Django 5.0 on 2023-12-10 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_name', models.CharField(max_length=100)),
                ('comp_field', models.CharField(max_length=100)),
                ('comp_discription', models.TextField()),
            ],
        ),
    ]
