# Generated by Django 5.0 on 2023-12-10 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companies',
            name='comp_discription',
        ),
        migrations.RemoveField(
            model_name='companies',
            name='comp_field',
        ),
    ]
