# Generated by Django 5.0 on 2023-12-10 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_companies_comp_discription_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='companies',
            new_name='company',
        ),
    ]
