# Generated by Django 5.0 on 2024-01-02 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_job_company_name_job_salary_job_working_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='c_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.job'),
        ),
    ]
