# Generated by Django 4.2.7 on 2023-12-19 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myhospitals', '0004_bookings'),
    ]

    operations = [
        migrations.CreateModel(
            name='name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
            ],
        ),
    ]
